### ISSUE TITLE
Maybe flag up if post scores below -5

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/modreportbot#5]
Considering flagging up posts that go below -5.
This would need some additional scanning of communities which the bot isn't doing currently.

**Comment by chris-y** [comment]
Submitted PR so we can use Lemmy's Moderator View, which will make this possible:
https://github.com/db0/pythorhead/pull/100

**Comment by M4rtineski** [comment]
Yeah, flagging posts in negatives sounds like a good idea to be alarmed of something happening.

**Comment by chris-y** [comment]
I've also found a use for the "mark as read" option - I can mark posts that have been processed and ignore them next time!

**Comment by M4rtineski** [comment]
Cool! But how it will flag negative posts then though?

**Comment by chris-y** [comment]
Fair point. I guess it only marks them as read if they've triggered the threshold.

**Comment by M4rtineski** [comment]
Process them only after x amount of time to give people time to put their votes maybe?

**Comment by M4rtineski** [comment]
Or maybe just scan by "controversial" every so often.  Don't know if the sort works like I think it does.

**Comment by chris-y** [comment]
Added in 4c952aca9bac0fe735ce6c216dfc1bde878c5bc1
